import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "BMW",
        logo: "/images/bmw.jpeg",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "2017 Golf R",
      category: "Hatchback",
      image: "/images/car1.jpg",
      price: 35998,
      countInStock: 10,
      brand: "Volkswagen",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "2018 330 XI",
      category: "Sedan",
      image: "/images/car2.jpg",
      price: 26998,
      countInStock: 20,
      brand: "BMW",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "500 Pop",
      category: "Hatchback",
      image: "/images/car3.jpg",
      price: 9599,
      countInStock: 0,
      brand: "Fait",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Benz SLK350",
      category: "Coupe",
      image: "/images/car4.jpg",
      price: 31998,
      countInStock: 15,
      brand: "Mercedes",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "2016 F250 Platinum ",
      category: "Pick up",
      image: "/images/car5.jpg",
      price: 59800,
      countInStock: 5,
      brand: "Ford",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Audi A3 Cabriolet",
      category: "Coupe",
      image: "/images/car6.jpg",
      price: 44998,
      countInStock: 12,
      brand: "Audi",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
